name:                bits-extra
version:             0.0.0.1
github:              "githubuser/bits-extra"
license:             BSD3
author:              "John Ky"
maintainer:          "newhoggy@gmail.com"
copyright:           "2018 John Ky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/bits-extra#readme>

dependencies:
- base >= 4.11 && < 5
- ghc-prim

library:
  source-dirs: src

tests:
  bits-extra-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bits-extra
    - hspec
    - hedgehog

benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench
    dependencies:
    - base >=4 && <5
    - bits-extra
    - criterion
    - hw-bits
    - hw-prim >=0.4.0.0
    - vector
    when:
    - condition: flag(sse42)
      then:
        ghc-options:
        - -Wall
        - -O2
        - -msse4.2
      else:
        ghc-options:
        - -Wall
        - -O2


