name: bits-extra
version: '0.0.1.2'
synopsis: Useful bitwise operations
description: Please see the README on Github at <https://github.com/haskell-works/bits-extra#readme>
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2018 John Ky
license: BSD3
category: Data, Serialization
github: haskell-works/bits-extra
extra-source-files:
- ChangeLog.md
- README.md
tested-with: GHC == 8.4.2, GHC == 8.2.2, GHC == 8.0.2, GHC == 7.10.3

dependencies:
- ghc-prim

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2
  exposed-modules:
  - Data.Bits.BitSize
  - Data.Bits.Pdep
  - Data.Bits.Pdep.Slow
  - Data.Bits.Pext
  - Data.Bits.Pext.Slow
  dependencies:
  - base >=4.8 && <5
  - vector
  when:
  - condition: (flag(bmi2)) && (impl(ghc >=8.4.1))
    ghc-options:
    - -mbmi2
    - -msse4.2
    cpp-options:
    - -DBMI2_ENABLED

tests:
  bits-extra-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >=4.8 && <5
    - bits-extra
    - hedgehog
    - hspec
    - hw-hedgehog
    - hw-hspec-hedgehog
    verbatim:
      build-tool-depends:
        "hspec-discover:hspec-discover"
    when:
    - condition: (flag(bmi2)) && (impl(ghc >=8.4.1))
      ghc-options:
      - -mbmi2
      - -msse4.2

benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -Wall
    - -O2
    dependencies:
    - base >=4.8 && <5
    - bits-extra
    - criterion
    - vector
    when:
    - condition: (flag(bmi2)) && (impl(ghc >=8.4.1))
      ghc-options:
      - -mbmi2
      - -msse4.2

flags:
  bmi2:
    description: Enable bmi2 instruction set
    manual: false
    default: false
